### ISSUE TITLE
Adding Tests and fixing failures

### ISSUE THREAD

**Issue by esnowgol** [esnowgol/myMiniCanvas#1]
**User Story**
As a developer, I want to make sure my software is thoroughly tested and functional so that Users do not encounter any errors.

**Tasks**
- [ ] All the methods in the repository should have at least one unit test
- [ ] The coverage of the tests should be as high as possible
- [ ] Use Mocker to test behaviors appropriately
- [ ] Use fixture to let your tests be as DRY (don't-repeat-yourself) as possible
- [ ] The initial code from the repository is not perfect, make sure to fix any issues that your tests reveal.
- [ ] The final backend app should handle all the invalid inputs and throw appropriate error messages.

**Acceptance Criteria**
All code is functional, and test functions are created for the purpose of validating the functionality as well.

**Acceptance Tests**
All Testing functions work properly, and also properly test the code our user will be utilizing.
